OCI builder: use a debian image
the github release workflow fails randomly with this type of error:

```
error: linking with `cc` failed: exit status: 4
```

```
note: cc: internal compiler error: Segmentation fault signal terminated program collect2
      Please submit a full bug report, with preprocessed source (by using -freport-bug).
      See <https://gitlab.alpinelinux.org/alpine/aports/-/issues> for instructions.
```

Opened issue : https://gitlab.alpinelinux.org/alpine/aports/-/issues/16813

Not sure if it is really caused by something alpine related, so testing
with debian...